export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';
export const ADD_PAGE = 'ADD_PAGE';
export const SET_PAGE = 'SET_PAGE';
export const SET_KEYWORDS = 'SET_KEYWORDS';
